### ISSUE TITLE
Looks like this is broken in jQuery 3.3.1

### ISSUE THREAD

**Issue by vbbalaji** [abhiomkar/portfolio-js#50]
Im using JQ 3.3.1 and Im getting a warning and error.

Warning: jquery-3.3.1.min.js:2 jQuery.Deferred exception: portfolioEl.querySelector is not a function TypeError: portfolioEl.querySelector is not a function
    at new Portfolio (https://unpkg.com/portfolio-js@2.1.5/dist/portfolio.umd.js:26:31)
    at HTMLDocument.<anonymous> (http://localhost/mysupport/customers/customers.html:408:9)
    at l (http://localhost/mysupport/js/jquery-3.3.1.min.js:2:29375)
    at c (http://localhost/mysupport/js/jquery-3.3.1.min.js:2:29677) undefined

Error: jquery-3.3.1.min.js:2 Uncaught TypeError: portfolioEl.querySelector is not a function
    at new Portfolio (portfolio.js:14)
    at HTMLDocument.<anonymous> (customers.html:408)
    at l (jquery-3.3.1.min.js:2)
    at c (jquery-3.3.1.min.js:2)

**Comment by juanem1** [comment]
@vbbalaji you can use a workaround:
`
new Portfolio(
    document.querySelector('.my-image-gallery')
);
`

**Comment by webbrain-one** [comment]
👋 Thanks for reporting this! I've opened a PR that fixes the `portfolioEl.querySelector` error you're seeing with jQuery 3.3.1. You can view the fix here: https://github.com/abhiomkar/portfolio-js/pull/51

Hope this helps!
